# Generated by Django 2.2 on 2020-03-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.TextField(max_length=200)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=30000)),
                ('address', models.TextField(max_length=100000)),
                ('city', models.CharField(max_length=5000)),
                ('district', models.CharField(max_length=5000)),
                ('state', models.CharField(max_length=20000)),
                ('bank_name', models.CharField(max_length=20000)),
            ],
        ),
    ]
