# Generated by Django 2.2 on 2020-02-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_info',
            fields=[
                ('ifsc', models.TextField(max_length=200, primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField(max_length=50)),
                ('branch', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=1000)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
            ],
        ),
    ]
