# Generated by Django 2.2 on 2020-02-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_info',
            name='bank_id',
            field=models.IntegerField(),
        ),
    ]
