# Generated by Django 2.2 on 2020-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200215_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_info',
            name='address',
            field=models.TextField(max_length=100000),
        ),
    ]
