# Generated by Django 2.2 on 2020-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20200215_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_info',
            name='bank_name',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='bank_info',
            name='branch',
            field=models.CharField(max_length=30000),
        ),
        migrations.AlterField(
            model_name='bank_info',
            name='city',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='bank_info',
            name='district',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='bank_info',
            name='state',
            field=models.CharField(max_length=20000),
        ),
    ]
